version: "3.7"

services:
  django:
    image: fantasmas/friendscal 
    restart: always
    expose:
      - "8000"
    volumes:
      - ./project/media:/code/media
      - ./project/staticfiles:/code/staticfiles
    command: gunicorn -w 3 djangoproject.wsgi:application --bind 0.0.0.0:8000
    networks:
      - django-network
    env_file: django.env
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data/
    networks:
      - django-network
    env_file: db.env

  nginx:
    image: nginx:1.17-alpine
    restart: always
    expose:
      - "80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./project/staticfiles:/code/staticfiles
      - ./project/media:/code/media
    networks:
      - django-network
      - traefik-network
    depends_on:
      - django
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.friendscal-insecure.rule=Host(`friends.lutz.fyi`)"
      - "traefik.http.routers.friendscal-insecure.entrypoints=web"
      - "traefik.http.routers.friendscal-insecure.middlewares=httpsredirect@file"
      - "traefik.http.routers.friendscal.rule=Host(`friends.lutz.fyi`)"
      - "traefik.http.routers.friendscal.entrypoints=web-secure"
      - "traefik.http.routers.friendscal.tls.certresolver=letsencrypt"
      - "traefik.http.services.friendscal.loadbalancer.server.port=80"

networks:
  django-network:
    driver: bridge
  traefik-network:
    external: true
    name: proxy_traefik-network
